### ISSUE TITLE
Which configurations should we test on?

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#132]
In the process of dealing with #131 I noticed that we test on an odd combination of python versions and operating systems.

Currently:
```
Linux 3.8,3.7,3.6
Mac   3.7
Win   3.8,3.7
```

3.9 has been out about a month now, but quiet a few things orix runs with (pyxem for one) can't make it work yet. Assuming we are happy with two versions, three operating systems shall we go 3.8,3.7 for v0.5.x and consider bumping ourselves into 3.9 for 0.6 ~ given how low-level most of this code is, I would be surprised if we weren't compatible with everything.

**Comment by hakonanes** [comment]
At a minimum we should make sure orix supports the lowest Python versions pyxem and kikuchipy supports, which is 3.7, reflected in both projects `setup.py` and Travis CI builds.

Since we already test 3.6, I would like to keep that unless the number of builds is too large. I assume we're okay with saying orix supports 3.6 although this is only tested on Linux?

I'll try to build kikuchipy with 3.9 locally and see what happens.

**Comment by pc494** [comment]
I will add support for Mac 3.8 for now and we can revisit at the time of our next minor release.
