### ISSUE TITLE
Consider the usage of orix.scalar.Scalar

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#198]
> Actually, I avoid using `orix.scalar.Scalar` wherever I can, because I don't like writing and reading code where the `.data` is 
> needed to get the NumPy array. I haven't looked at the reason why we need `Scalar`, it might a good one, perhaps it enables 
> us to not check for instance shapes or something similar, but I would be interested in seeing if we can remove completely.

_Originally posted by @hakonanes in https://github.com/pyxem/orix/issues/197#issuecomment-853942078_

I think this is a broadly fair assessment and worth looking into. The Scalar class can be a nuisance.

**Comment by harripj** [comment]
As @hakonanes mentioned this again in #264, it may be worth having a discussion here. From having looked at the code I don't know what benefit we get from the `Scalar` class rather than being an extra (unnecessary) abstraction over a NumPy array and extra `.data` calls. Personally I would be in favour of trying to remove it.
