### ISSUE TITLE
We should start to use Numba

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#219]
After optimizing generation of a dictionary of simulated EBSD patterns from a master pattern in kikuchipy ([code in open PR](https://github.com/pyxem/kikuchipy/pull/405/files#diff-600ddf9a30919bf272396e055cbbac22ce79d8b443ce705524e7d3e22e29a14fR19)), I'm starting to think we should start to use Numba in orix. This can sometimes mean moving away from always using vectorized operations, and instead using a for loop in a function decorated with Numba.

I've for example written a [Numba version](https://github.com/pyxem/kikuchipy/pull/405/files#diff-600ddf9a30919bf272396e055cbbac22ce79d8b443ce705524e7d3e22e29a14fR289) of the orix quaternion multiplication of one quaternion with many vectors, as part of the mentioned PR. That gave me a huge speed up over doing it vectorized.

If we find the time, I suggest we start small by providing Numba versions of calculations like this, and move on from there. How this would be available via the public API, I don't have a suggestion for yet.

**Comment by pc494** [comment]
This is an excellent idea, in your experience how well have `numba` and `dask` played with one another?

**Comment by hakonanes** [comment]
> in your experience how well have `numba` and `dask` played with one another?

i should say that my experience is limited.

i think they work seamlessly together. to generate a dictionary of simulated patterns, we separate the rotations array into chunks and fill the dictionary chunk by chunk. the chunking logistics are handled by dask. it calls a numba decorated get_chunk function, which loops over the rotations one at a time. everything within get_chunk uses numpy, the function has no reference to anything dask related.

i havent timed the speed-up yet since im still working on optimizing, but it is worth the effort, at least.

**Comment by pc494** [comment]
cool, good issue - might stay open for a while!

**Comment by hakonanes** [comment]
Started to use Numba in #221.

I've thought a bit about the use of Numba in kikuchipy, and I think it is best to just use Numba wherever we find it useful in the code, and not try to "centralize" all Numba functions in one place, like its own module.

I also suggest we close this issue, but try to be mindful of situations whenever it becomes helpful or necessary to use? I find it mostly useful whenever I find I have to use for loops because vectorizing becomes challenging for some logic or computation.

**Comment by pc494** [comment]
Sounds good to me, #221 provides amble evidence that numba can help a lot

**Comment by din14970** [comment]
> This is an excellent idea, in your experience how well have numba and dask played with one another?

Dask doesn't care about numba but in general using numba with dask is preferable because of the GIL. When using the single machine scheduler, dask schedules tasks on threads (default) or in processes. Python does not have actual multithreading due to the GIL, meaning that when you ask dask to "compute" things in parallel with multiple workers on separate threads it will only work on one thread at any one time when the GIL is not released. This is the case for most python code, and so this code will not see any speedup with dask's threads scheduler. In order to actually parallelize python code with dask, you must compute with the "processes" scheduler, but this requires individual python interpreters to be spun up for each, and may cause undue pressure on machine memory since processes can't share memory (so copies will be created of most things). Dask's threads scheduler works great for compiled code like numpy, pandas, ... which is actually just C code and does not block the GIL. Calls to numpy functions can be executed in parallel while still sharing memory. Turns out you can also release the GIL by compiling your python code with numba: see `nogil` option https://numba.pydata.org/numba-doc/latest/user/jit.html#compilation-options.  So with numba you can create truly thread parallelizable functions equivalent to numpy or pandas functions. So the more you can avoid python code that needs to go through the interpreter, the more the code can be parallelized and sped up.
For info on these dask schedulers, see https://docs.dask.org/en/latest/setup/single-machine.html#single-machine-scheduler 

> That gave me a huge speed up over doing it vectorized.

Numba can be faster than numpy  because of 2 main reasons. First numpy functions take in a bunch of arguments that must be dealt with internally by complex control logic. The "dumber" and simpler you make your algorithm for a specific case, the more the compiler can optimize the code and make it faster. If numpy's vectorized implementation is faster it means that the algorithm you implemented in numba is probably inferior and there's a better way to do it. Secondly, as far as I know numpy is single threaded. This is a big reason why dask exists - to parallelize numpy operations. If you use numba's `prange` and `parallel=True` then your `jit` function will parallelize for loops onto different threads, making it faster than equivalent single-threaded numpy functions. How Numba's multithreading interacts with dask's multithreading I have not yet been able to figure out though.

One important thing to note is that debugging numba code is very painful and error messages are not useful at all. You also suddenly make it possible to get all kinds of fun memory errors that you might get with C/C++. For example, the following is perfectly valid numba code which will not raise any errors and will produce bogus results:

```python
@njit
def access_forbidden(a):
    return a[3]
    
a = np.array([1, 2])
access_forbidden(a)
```

You can also directly overwrite memory that you shouldn't have access to making it much more dangerous. Also test coverage will no longer work on these lines, since the python interpreter never "sees" them. As far as the python interpreter is concerned, njit functions are black boxes. So one has to just make sure that the black box is very very solid.

**Comment by hakonanes** [comment]
Thanks for the input @din14970, much here I didn't know. I've just started using Numba, and for not that complicated stuff, I think. Using it in combination with CuPy *and* Dask (we use it with Dask in kikuchipy), as you have @din14970, sounds more complex and thus challenging to debug and optimize. However, I'd like to point out a few things I've found OK about Numba.

> as far as I know numpy is single threaded

I believe this is true for much of the library, but not everything. On my machine, the following uses all my four CPUs: `import numpy as np; np.dot(np.random.random((10000, 20000)), np.random.random((20000, 10000)))`.

> debugging numba code is very painful and error messages are not useful at all.

I've only encountered error messages upon compilation, i.e. upon loading a module with a Numba JITed function, before running anything. I find these error messages highly informative. They mostly tell me which NumPy functions they don't have an implementation for certain array shapes and data types. And when I pass in an array of incorrect shape or data type, I'm told so. Do you mean error messages different from these?

> For example, the following is perfectly valid numba code which will not raise any errors and will produce bogus results

That example is scary! I didn't know that was possible.

> Also test coverage will no longer work on these lines, since the python interpreter never "sees" them

You can test Numba JITed functions, say a function named `_rotation_to_euler()`, by calling `_rotation_to_euler.py_func()`, and thus Coverage.py picks up the lines. All Numba JITed lines in kikuchipy and in #221 are covered.

**Comment by din14970** [comment]
> You can test Numba JITed functions, say a function named _rotation_to_euler(), by calling _rotation_to_euler.py_func()

TIL, thanks

> I believe this is true for much of the library, but not everything

Again TIL

> I've only encountered error messages upon compilation, i.e. upon loading a module with a Numba JITed function, before running anything. I find these error messages highly informative.

Compilation errors are indeed reasonably good, but occasionally you might hit on something weird. For example, I have a function where I use the elements of one array to index into another array. To do so, the elements of the first array must be of the `int` type and can not be of the `uint` type. I seem to remember it took me a long time to figure that one out because it does work when it's not JIT compiled, but not when you use JIT.

The main challenge are unexpected runtime errors, like the simple example. Then you can basically just get a segfault.

**Comment by hakonanes** [comment]
> For example, I have a function where I use the elements of one array to index into another array. To do so, the elements of the first array must be of the `int` type and can not be of the `uint` type.

Yes, this has stumped me many times, to the point where I've started to explicitly specify the input and output data types and array shapes in the `numba.jit()` "signature", so that I get an error I can understand when I pass an array of an invalid shape or data type...

This specific problem actually makes me think that, at least for the code I write, Numba JITed functions should only be used internally; no API functions where the input array shapes and data types cannot be checked before hand should be JITed. This will hopefully save the user some trouble.
