### ISSUE TITLE
On the use of data_dim

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#227]
Just wanted to open a discussion about navigation dimensions and access.

Personally I have found myself trying to call the attribute ```.ndim``` on almost all instances (```Orientation```, ```Vector3d```) to get the number of navigation dimensions (not the full data ndim as last dimension ```dim``` is hidden from the user for the most part) and have been considering adding this to ```Object3d```.

I have found that ```.data_dim``` produces this result, but personally, coming from NumPy, I was searching for ```.ndim``` in the docs. I am also not sure whether ```.data_dim``` is the clearest attribute name for this, as its doctsring doesn't reference that it provides access to the number of navigation dimensions.

I would like to get other peoples feelings on this, and whether ```.data_dim``` is well used within your workflows?

I would have a couple the suggestion to add ```.ndim``` attribute to ```Object3d``` and either:

1. maintain alongside ```.data_dim```
2. replace ```.data_dim```.

My feeling is that ```.ndim``` is natural for those familiar with NumPy. The drawback to this would be that ```Object3d.data.ndim``` and ```Object3d.ndim``` give different values, but this is also the case with ```.shape```, so I think it is consistent behaviour.

In any case I think the docstring for both attributes should describe that they provide access to just the navigation dimensions.

**Comment by hakonanes** [comment]
> I was searching for `.ndim` in the docs.

The API reference aren't perfect, and they have great room for improvement in my opinion. I'm slowly updating docstrings in the parts of the code I touch in PRs. Please feel free to make PRs with just docstring updates if you find something lacking and you find the time.

> I would like to get other peoples feelings on this, and whether `.data_dim` is well used within your workflows?

I always use `len(rotations.shape)` to get number of dimensions ([example use in kikuchipy](https://github.com/pyxem/kikuchipy/blob/develop/kikuchipy/generators/ebsd_simulation_generator.py#L87)), but that is because I haven't considered using the `data_dim` property at all!

> I would have a couple the suggestion to add `.ndim` attribute to `Object3d` and either:
>     1. maintain alongside `.data_dim`
>     2. replace `.data_dim`.

`data_dim` -> `ndim` is my preference, but over one minor release, meaning that we deprecate `data_dim` in favour of `ndim` in v0.7.1, so that any usage out in the wild of `data_dim` will get a warning. Then, in v0.8.0, we remove `data_dim`. I'm not aware of any other released packages using orix than pyxem, diffsims, and kikuchipy. If none of these packages use `data_dim`, I think not end users should be bothered by these warnings. We recently added a [deprecated decorator](https://github.com/pyxem/orix/blob/master/orix/_util.py#L38) for functions/methods taken from scikit-image and matplotlib. I can help to add one for attributes as well.

> My feeling is that `.ndim` is natural for those familiar with NumPy. The drawback to this would be that `Object3d.data.ndim` and `Object3d.ndim` give different values, but this is also the case with `.shape`, so I think it is consistent behaviour.

Agree.

---

Would be good to get a second opinion on this from other maintainers before making the changes.

**Comment by hakonanes** [comment]
Also, since it seems you're using orix in your work, I would like to encourage you to update existing or create new [user guide notebooks](https://orix.readthedocs.io/en/stable/) if you find anything you would like to add or change!

**Comment by pc494** [comment]
Basically agree with all of the above, except I would opt to run both in version 0.8.0 (rerouting `data_dim` through `ndim` with a warning) and then remove `data_dim` in 0.9 - mainly because I'm not sure how diligently people pull down patch requests.


If nothing else we should change the below example so that the tuple is `(4,5,6)` - gave me pause for thought when I looked at it.

https://github.com/pyxem/orix/blob/1031bcc82fab89db3918419fde21943eae784f79/orix/base/__init__.py#L116

**Comment by harripj** [comment]
I will make a PR, and agree with the example above @pc494.

**Comment by hakonanes** [comment]
Resolved in #228.
