### ISSUE TITLE
Need better documentation of the alignment of direct and reciprocal reference frames

### ISSUE THREAD

**Issue by ravipurohit1991** [pyxem/orix#236]
Hello,
I have been trying to get equivalent HKL vectors provided a given symmetry. However I don't get exactly what I want. Maybe I have not called the right functions. Could you please help. Below is the snippet of the code that I have used.

```python
from diffpy.structure import Structure as strucdiffpy
from orix.crystal_map import Phase
from orix.vector import Miller

a, b, c, alpha, beta, gamma = 5.1505, 5.2116, 5.3173, 90, 99.23, 90
#For space group 14, which is a monoclinic structure 2/m symetry
crystal = Phase(space_group=14, structure=strucdiffpy(lattice=latdiffpy(a, b, c, alpha, beta, gamma)))

#defining a HKL for which equivalent HKLs are required.
hkl_vector = np.array([3,-1,1])

m1 = Miller(hkl=hkl_vector , phase=crystal)

m2, mul = m1.symmetrise(unique=True, return_multiplicity=True)
```

now m2.hkl should give me the list of equivalent hkls, right ?
However, when I do  "_round_indices(m2.hkl)"

```python
Out[86]: 
array([[ 3, -1,  1],
       [-3,  1,  2],
       [ 3, -1, -2],
       [-3,  1, -1]])
```

What is bothering is the second and third row. I expect the below.

```python
array([[ 3, -1,  1],
       [-3,  1,  1],
       [ 3, -1, -1],
       [-3,  1, -1]])
```

Thank you for the help.
Ravi.

**Comment by hakonanes** [comment]
Hi @ravipurohit1991,

thanks for reporting this bug. I get the same results as you (using only public methods from the [API reference](https://orix.readthedocs.io/en/stable/reference.html#miller) and [user guide](https://orix.readthedocs.io/en/stable/crystal_geometry.html#Planes-(hkl))):

```python
>>> from diffpy.structure import Lattice, Structure
>>> from orix.crystal_map import Phase
>>> from orix.vector import Miller
>>> phase = Phase(
...     point_group="2/m",
...     structure=Structure(lattice=Lattice(5.1505, 5.2116, 5.3173, 90, 99.23, 90))
... )
<name: . space group: None. point group: 2/m. proper point group: 112. color: tab:blue>
>>> m1 = Miller(hkl=(3, -1, 1), phase=phase)
>>> m1
Miller (1,), point group 2/m, hkl
[[ 3. -1.  1.]]
>>> m2 = m1.symmetrise()
>>> m2
Miller (4,), point group 2/m, hkl
[[ 3.     -1.      1.    ]
 [-3.      1.      1.9936]
 [ 3.     -1.     -1.9936]
 [-3.      1.     -1.    ]]
>>> m2.round()
Miller (4,), point group 2/m, hkl
[[ 3. -1.  1.]
 [-3.  1.  2.]
 [ 3. -1. -2.]
 [-3.  1. -1.]]
```

The cartesian coordinates (xyz), used internally, are at least identical (except for signs)

```python
>>> m2.data  # cartesian coordinates xyz
array([[ 0.58246772, -0.19187965,  0.2851845 ],
       [-0.58246772,  0.19187965,  0.2851845 ],
       [ 0.58246772, -0.19187965, -0.2851845 ],
       [-0.58246772,  0.19187965, -0.2851845 ]])
```

so I think you've highlighted some error in calculating [hkl from cartesian coordinates](https://github.com/pyxem/orix/blob/master/orix/vector/miller.py#L708) or [cartesian coordinates from hkl](https://github.com/pyxem/orix/blob/master/orix/vector/miller.py#L716), or both...

I hope to find time to fix this issue soon, but help with pinpointing the issue would be very much appreciated. We should include this example as a test to make sure that we get the expected results after identifying the bug.

**Comment by ravipurohit1991** [comment]
Hello @hakonanes 
Thank you for the quick reply. I will try to look more into the code in detail to see if I can find something related to this issue.

Ravi.

**Comment by hakonanes** [comment]
The issue here is a lack of documentation, so its not a bug. What to expect from applying symmetry operations would be more clear to users like you @ravipurohit1991 and me (!) if we (1) stated the alignment of the direct and reciprocal reference frames, and (2) added some plotting of the symmetry operations. This should be the conclusion from this issue. 

### Solution
In short, if you switch your b and c axes, you get your expected result:

```python
>>> from diffpy.structure import Lattice, Structure
>>> from orix.crystal_map import Phase
>>> from orix.vector import Miller
>>> phase = Phase(
...     point_group="2/m",
...     structure=Structure(lattice=Lattice(5.1505, 5.3173, 5.2116, 90, 90, 99.23))
... )
>>> m1 = Miller(hkl=(3, -1, 1), phase=phase)
>>> m1.symmetrise()
Miller (4,), point group 2/m, hkl
[[ 3. -1.  1.]
 [-3.  1.  1.]
 [ 3. -1. -1.]
 [-3.  1. -1.]]
```

### Explanation

orix defines the 2/m symmetry operations as a combination of a two fold rotation about Z combined with a mirror plane with the plane normal parallel with Z, while MTEX uses a two fold rotation about Y combined with a mirror plane with the plane normal parallel to Y. We can illustrate this by rotating the (3 -1 1) vector by the symmetry operations used in orix and MTEX

```python
>>> from orix.quaternion import Symmetry
>>> from orix.vector import Vector3d
>>> operations_orix = Symmetry((
...     (1, 0, 0, 0),
...     (0, 0, 0, 1),
...     (0, 0, 0, 1),
...     (1, 0, 0, 0)
... ))
>>> operations_orix.improper = (False, False, True, True)
>>> operations_orix.axis
Vector3d (4,)
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
>>> operations_orix.angle
Scalar (4,)
[0.     3.1416 3.1416 0.    ]
>>> operations_mtex = symmetry.Symmetry((
...     (1, 0, 0, 0),
...     (0, 0, 1, 0),
...     (1, 0, 0, 0),
...     (0, 0, 1, 0),
... ))
>>> operations_mtex.improper = (False, False, True, True)
>>> operations_mtex.axis
Vector3d (4,)
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
>>> operations_mtex.angle
Scalar (4,)
[0.     3.1416 0.     3.1416]
>>> v = Vector3d((3, -1, 1))
>>> scatter_kwds = dict(c=["r", "g", "b", "y"], hemisphere="both", axes_labels=("x", "y", None))
>>> (operations_orix * v).scatter(**scatter_kwds)
>>> (operations_mtex * v).scatter(**scatter_kwds)
```

Results with orix' 2/m:
![orix](https://user-images.githubusercontent.com/12139781/140766840-101bc6f3-49fb-4291-a9ab-4f4fa170b292.png)

Results from MTEX 2/m:
![mtex](https://user-images.githubusercontent.com/12139781/140766872-80e2dd34-169e-41fc-944e-78e887236d09.png)

Going further, we can use `operations_mtex` instead of `operations_orix`, which is equivalent to the built in `orix.quaternion.symmetry.C2h` (2/m), to get your desired results without exchanging b and c (continuing last code block):

```python
>>> phase = Phase(
...     point_group=None,
...     structure=Structure(lattice=Lattice(5.1505, 5.2116, 5.3173, 90, 99.23, 90))
... )
>>> phase.point_group = operations_mtex
>>> m1 = Miller(hkl=(3, -1, 1), phase=phase)
>>> m1.symmetrise()
Miller (4,), point group , hkl
[[ 3. -1.  1.]
 [-3. -1. -1.]
 [-3.  1. -1.]
 [ 3.  1.  1.]]
```

**Comment by hakonanes** [comment]
The difference in the alignment of the two fold axis in 2/m between orix and MTEX is also evidenced in the fact that with MTEX' *2/m* the proper point group (no improper rotations, that is no inversions) is *121*, while with orix' *2/m* it's *112*.

**Comment by ravipurohit1991** [comment]
Hello @hakonanes ,

Thank you for this nice explanation. It is much clearer now. I was wondering the reference frame issue and your last comment has perfectly demonstrated this. For me the issue can be closed. 

Thanks again for the quick help,
Ravi.

**Comment by hakonanes** [comment]
I'm glad you find the explanation satisfactory! As you say, the issue is the definition of the reference frames.

I'd like to keep this issue open but change the issue title, so that we'll remember to add better (/any) documentation of the crystal reference frame alignments. Again, thank you for reporting this issue!
