### ISSUE TITLE
Whether to use type hints in function/method signatures

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#68]
I used function/method signature type hints in the initial commits in #66, but decided to leave them for another PR since we haven't decided whether to use them or not (https://github.com/pyxem/orix/pull/66#pullrequestreview-430441109).

Why I want to use them:
* The editor I use, PyCharm, picks up these signatures type hints. It then tells me when I'm trying to pass something of the "wrong" type or use a return argument in the wrong way. I find this quite useful when coding.
* I understand what a function takes and returns quicker with type hints, instead of looking through the docstring.

So, we don't gain that much by introducing them, but we gain more than we lose, in my opinion.

**Comment by dnjohnstone** [comment]
I'm always a bit conflicted about this - but overall I think that type hints make it easier to avoid type related bugs when developing new scripts using our code and it may make development/maintenance easier when working on parts of code that a particular person hasn't touched in a while.

Another advantage is that we can automate type checking using mypy, so it should be easier to keep up to date than docstrings, which sometimes get out of date and are hard to automatically check.

What do you think @pc494 ?

**Comment by pc494** [comment]
I'm on the orthodox side of this fence, and in general opposed to type checking in basically any form. It's my belief that well named code will guide a user cleanly, and the addition of extra lines for type checking makes a developers life more challenging. 

All that said, it seems Python is moving a little closer to type checking, and if we decide to transfer over to type checking at a given release cycle I would be on board with that.

**Comment by hakonanes** [comment]
OK, should we leave this issue open and decide for now to not use them? That's fine by me.

**Comment by dnjohnstone** [comment]
Thinking about this a bit more - I think we should consider that when PEP484 introduced these type hints it was presumably because lots of people find it helpful. It doesn't actually impost static typing nor is it doing type checking, only providing the reference list of expected types for subsequent type checking whether at runtime or in IDEs. In other words, it's just a particular and, importantly, standardised form of documentation.

To my mind, like other documentation, type annotation has to make it easier to understand  the code when you're coming at it cold i.e. new users or new contributors. The fact that it also enables automated type checking is potentially useful. Currently we should be maintaining the docstrings to express this information so the additional development overhead seems quite minimal to me. The only downside I see is that it's a lot of extra characters to read and I'm not very used to looking at code written like that.

I think we've probably all had occasions where we've had type related bugs and while we can probably solve them relatively quickly, this should make it faster.

So I think the only 2 questions I have right now are:

1. Are there any cases where we have functions that take multiple type objects that might cause issues?

2. How likely do we think this is to become the common form for major scientific python libraries (which I think we want to be vaguely consistent with). 

I had a quick look at scikit-learn and scikit-image and I don't think they use type hints yet - but maybe there are other examples that are more similar to orix.

**Comment by hakonanes** [comment]
A good summary, my view aligns with yours.

The `napari` project is more like `scikit-image` than `orix`, but they have give type hints both in docstrings and function/method signatures, see e.g. https://github.com/napari/napari/blob/master/napari/plugins/io.py. And, as I see now, they use it also for inline code, at least for some variables.

**Comment by dnjohnstone** [comment]
I think that we should make a decision on this for v1.0.0, which will then lock it in for ca. 1 year.

My personal preference is to not do it and then just close this, but happy to be persuaded.
