### ISSUE TITLE
Update following matplotlib v3.3 changes in how `aspect` works

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#76]
A cursory glance suggests this is due to `matplotlib` going to v3.3 (from v3.2)

**Comment by hakonanes** [comment]
I'm making a patch for this.

Two errors:
1. when checking if scalebar attributes are set correctly when passing scalebar properties to `CrystalMapPlot.add_scalebar()`. Fixed by changing the attribute to look for.
2. when trying to set `aspect="equal"` when making a rotation plot. Setting to "auto", which is the only option in Matplotlib v3.3, fixed it. **Is this acceptable?**

I had to install `pip install matplotlib==3.3` in my conda env after trying `conda update --all`, where it weren't available.

**Comment by hakonanes** [comment]
Okay, the following code (the test) produces the following plots:

```python
import matplotlib.pyplot as plt
from orix import plot
from orix.quaternion.orientation import Misorientation, OrientationRegion
from orix.symmetry import D6


misori = Misorientation([1, 1, 1, 1])  # any will do
fig = plt.figure(figsize=(6, 3))
gridspec = plt.GridSpec(1, 1, left=0, right=1, bottom=0, top=1, hspace=0.05)
ax_misori = fig.add_subplot(
    gridspec[0], projection="axangle", proj_type="ortho", aspect="equal"  # Or "auto"
)
ax_misori.scatter(misori)
ax_misori.plot(misori)
ax_misori.plot_wireframe(OrientationRegion.from_symmetry(D6, D6))

# clear the edge case
ax_misori.transform(np.asarray([1, 1, 1]))

fig.savefig("/home/hakon/aspect_equal.png")  # Or auto
```
`aspect="equal"`
![aspect_auto](https://user-images.githubusercontent.com/12139781/87858778-b0cc1780-c930-11ea-9931-37947664ea3a.png)
`aspect="auto"`
![aspect_equal](https://user-images.githubusercontent.com/12139781/87858781-b4f83500-c930-11ea-963b-5f834cb188a6.png)

**Comment by hakonanes** [comment]
Seems like matplotlib v.3.3 via conda-forge is just right the corner: https://github.com/conda-forge/matplotlib-feedstock/pull/254

**Comment by tacaswell** [comment]
There are definitly very intentional changes to how 3D axes aspect works which were intended to fix long-standing issues.

See https://matplotlib.org/3.3.0/users/whats_new.html#d-axes-improvements

**Comment by dnjohnstone** [comment]
>     2\. when trying to set `aspect="equal"` when making a rotation plot. Setting to "auto", which is the only option in Matplotlib v3.3, fixed it. **Is this acceptable?**

Ok, great - I guess we have to update the test to use aspect="auto" if that's the only option in v3.3 - although presumably we don't actually have to set it if there aren't actually any options for this kwarg now. So I think that's the correct/only solution and I'll merge #77 

In terms of what we want - there was probably a reason that we previously set aspect="equal" - I have a vague recollection that it was because I thought the aspect="equal" plot above was a more intuitive representation of the fundamental zone insofar as the ratio of the z- and x- extents looked more like the ratio of the corresponding angular limits...

Anyway - that is not an issue for this test, but we might want to think about it in demo notebooks. If I've understood the new 3.3.0 info correctly we can play with this using the set_box_aspect() method and ultimately it's for individual users to decide about.

**Comment by dnjohnstone** [comment]
@pc494 - having just run through the demo notebooks again the aspect="equal" was so that fundamental zones that are the same dimensions in all directions look like they are when playing with the plot. I think we want that behaviour - so I think we're going to need to find a work around here...

**Comment by pc494** [comment]
From tacswell's link:

"Currently, modes of setting the aspect (via set_aspect) in data space are not supported for Axes3D but may be in the future. If you want to simulate having equal aspect in data space, set the ratio of your data limits to match the value of get_box_aspect. To control these ratios use the set_box_aspect method which accepts the ratios as a 3-tuple of X:Y:Z. The default aspect ratio is 4:4:3" ~ I'm happy to take it on, potentially for a patch as well as for v0.4.0?

**Comment by dnjohnstone** [comment]
Yeah I think this boils down to whether we just let individuals use `set_box_aspect` in notebooks as they like and probably update the demo notebooks to do that, or else we try to bake it in to the `RotationPlot` class. I'm not so bothered between those two although I kind of feel as though the first option is more in keeping with how we've approached plotting in general. In any case, I think one to resolve for 0.4.0

**Comment by pc494** [comment]
@hakonanes I feel like you fixed this at some point?

**Comment by hakonanes** [comment]
Yes! See [this notebook](https://orix--196.org.readthedocs.build/en/196/clustering_across_fundamental_region_boundaries.html#Visualisation) built PR #196. We want to use use `ax.set_box_aspect((1,) * 3)` where `ax` is a `Axes3D` ([matplotlib documentation](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_box_aspect)).

**Comment by pc494** [comment]
Great, I'm closing this then.
